name: new-workflow
env:
  IMAGE_REPOSITORY: waterfox83/covid-country-service
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
jobs:
  # Run all unit tests.
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      # Check out the pull request's source code.
      - name: Check out source code
        uses: actions/checkout@v2
      # Setup Java.
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Print java version
        run: java -version
      # Run unit tests.
      - name: Run unit tests
        run: ./gradlew test
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2
      # Build the jar
      - name: Build
        run: ./gradlew clean build
      # Build and push container image.
      - name: Build and push container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          dockerfile: Dockerfile
          tag_with_ref: true